### ISSUE TITLE
Teensy 4.0

### ISSUE THREAD

**Issue by Pittyh** [DirectOutput/TeensyStripController#9]
Hello, 

Does this work with Teensy 4.0?

I keep getting errors

Arduino: 1.8.13 (Windows 10), TD: 1.53, Board: "Teensy 4.0, Serial, 600 MHz, Faster, US English"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\Daniel Walker\Documents\Arduino\libraries -fqbn=teensy:avr:teensy40:usb=serial,speed=600,opt=o2std,keys=en-us -vid-pid=16C0_0483 -ide-version=10813 -build-path C:\Users\DANIEL~1\AppData\Local\Temp\arduino_build_114999 -warnings=none -build-cache C:\Users\DANIEL~1\AppData\Local\Temp\arduino_cache_194824 -verbose C:\temp\Teensy 32\TeensyStripController\TeensyStripController.ino

C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\Daniel Walker\Documents\Arduino\libraries -fqbn=teensy:avr:teensy40:usb=serial,speed=600,opt=o2std,keys=en-us -vid-pid=16C0_0483 -ide-version=10813 -build-path C:\Users\DANIEL~1\AppData\Local\Temp\arduino_build_114999 -warnings=none -build-cache C:\Users\DANIEL~1\AppData\Local\Temp\arduino_cache_194824 -verbose C:\temp\Teensy 32\TeensyStripController\TeensyStripController.ino

Using board 'teensy40' from platform in folder: C:\Program Files (x86)\Arduino\hardware\teensy\avr

Using core 'teensy4' from platform in folder: C:\Program Files (x86)\Arduino\hardware\teensy\avr

Detecting libraries used...

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999\\sketch\\TeensyStripController.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999\\sketch\\OctoWS2811Ext.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Generating function prototypes...

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -E -CC -x c++ -w -g -Wall -ffunction-sections -fdata-sections -nostdlib -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999\\sketch\\TeensyStripController.ino.cpp" -o "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999\\preproc\\ctags_target_for_gcc_minus_e.cpp" -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Program Files (x86)\\Arduino\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999\\preproc\\ctags_target_for_gcc_minus_e.cpp"

Compiling sketch...

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/precompile_helper" "C:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr/cores/teensy4" "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999" "C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -x c++-header -O2 -g -Wall -ffunction-sections -fdata-sections -nostdlib -MMD -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr/cores/teensy4" "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999/pch/Arduino.h" -o "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999/pch/Arduino.h.gch"

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -c -O2 -g -Wall -ffunction-sections -fdata-sections -nostdlib -MMD -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999/pch" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999\\sketch\\TeensyStripController.ino.cpp" -o "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999\\sketch\\TeensyStripController.ino.cpp.o"

"C:\\Program Files (x86)\\Arduino\\hardware\\teensy/../tools/arm/bin/arm-none-eabi-g++" -c -O2 -g -Wall -ffunction-sections -fdata-sections -nostdlib -MMD -std=gnu++14 -fno-exceptions -fpermissive -fno-rtti -fno-threadsafe-statics -felide-constructors -Wno-error=narrowing -mthumb -mcpu=cortex-m7 -mfloat-abi=hard -mfpu=fpv5-d16 -D__IMXRT1062__ -DTEENSYDUINO=153 -DARDUINO=10813 -DARDUINO_TEENSY40 -DF_CPU=600000000 -DUSB_SERIAL -DLAYOUT_US_ENGLISH "-IC:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999/pch" "-IC:\\Program Files (x86)\\Arduino\\hardware\\teensy\\avr\\cores\\teensy4" "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999\\sketch\\OctoWS2811Ext.cpp" -o "C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\arduino_build_114999\\sketch\\OctoWS2811Ext.cpp.o"

C:\Users\DANIEL~1\AppData\Local\Temp\arduino_build_114999\sketch\OctoWS2811Ext.cpp: In member function 'void OctoWS2811Ext::begin()':

OctoWS2811Ext.cpp:94: error: 'GPIOD_PCOR' was not declared in this scope

  GPIOD_PCOR = 0xFF;

  ^

OctoWS2811Ext.cpp:119: error: 'FTM2_SC' was not declared in this scope

   FTM2_SC = 0;

   ^

OctoWS2811Ext.cpp:120: error: 'FTM2_CNT' was not declared in this scope

   FTM2_CNT = 0;

   ^

OctoWS2811Ext.cpp:121: error: 'F_BUS' was not declared in this scope

   uint32_t mod = (F_BUS + frequency / 2) / frequency;

                   ^

OctoWS2811Ext.cpp:122: error: 'FTM2_MOD' was not declared in this scope

   FTM2_MOD = mod - 1;

   ^

OctoWS2811Ext.cpp:123: error: 'FTM_SC_CLKS' was not declared in this scope

   FTM2_SC = FTM_SC_CLKS(1) | FTM_SC_PS(0);

                          ^

OctoWS2811Ext.cpp:123: error: 'FTM_SC_PS' was not declared in this scope

   FTM2_SC = FTM_SC_CLKS(1) | FTM_SC_PS(0);

                                         ^

OctoWS2811Ext.cpp:124: error: 'FTM2_C0SC' was not declared in this scope

   FTM2_C0SC = 0x69;

   ^

OctoWS2811Ext.cpp:125: error: 'FTM2_C1SC' was not declared in this scope

   FTM2_C1SC = 0x69;

   ^

OctoWS2811Ext.cpp:126: error: 'FTM2_C0V' was not declared in this scope

   FTM2_C0V = (mod * WS2811_TIMING_T0H) >> 8;

   ^

OctoWS2811Ext.cpp:127: error: 'FTM2_C1V' was not declared in this scope

   FTM2_C1V = (mod * WS2811_TIMING_T1H) >> 8;

   ^

OctoWS2811Ext.cpp:130: error: 'PORT_PCR_IRQC' was not declared in this scope

   CORE_PIN32_CONFIG = PORT_PCR_IRQC(1)|PORT_PCR_MUX(3);

                                      ^

OctoWS2811Ext.cpp:130: error: 'PORT_PCR_MUX' was not declared in this scope

   CORE_PIN32_CONFIG = PORT_PCR_IRQC(1)|PORT_PCR_MUX(3);

                                                      ^

OctoWS2811Ext.cpp:135: error: 'GPIOD_PSOR' was not declared in this scope

   dma1.destination(GPIOD_PSOR);

                    ^

OctoWS2811Ext.cpp:142: error: 'GPIOD_PDOR' was not declared in this scope

   dma2.destination(GPIOD_PDOR);

                    ^

OctoWS2811Ext.cpp:156: error: 'DMAMUX_SOURCE_PORTB' was not declared in this scope

   dma1.triggerAtHardwareEvent(DMAMUX_SOURCE_PORTB);

                               ^

OctoWS2811Ext.cpp:157: error: 'DMAMUX_SOURCE_FTM2_CH0' was not declared in this scope

   dma2.triggerAtHardwareEvent(DMAMUX_SOURCE_FTM2_CH0);

                               ^

OctoWS2811Ext.cpp:158: error: 'DMAMUX_SOURCE_FTM2_CH1' was not declared in this scope

   dma3.triggerAtHardwareEvent(DMAMUX_SOURCE_FTM2_CH1);

                               ^

C:\Users\DANIEL~1\AppData\Local\Temp\arduino_build_114999\sketch\OctoWS2811Ext.cpp: In member function 'void OctoWS2811Ext::show()':

OctoWS2811Ext.cpp:206: error: 'FTM2_C0SC' was not declared in this scope

   FTM2_C0SC = 0x28;

   ^

OctoWS2811Ext.cpp:207: error: 'FTM2_C1SC' was not declared in this scope

   FTM2_C1SC = 0x28;

   ^

OctoWS2811Ext.cpp:208: error: 'FTM2_C0V' was not declared in this scope

   uint32_t cv = FTM2_C0V;

                 ^

OctoWS2811Ext.cpp:211: error: 'FTM2_CNT' was not declared in this scope

   while (FTM2_CNT <= cv) ;

          ^

OctoWS2811Ext.cpp:212: error: 'FTM2_CNT' was not declared in this scope

   while (FTM2_CNT > cv) ; // wait for beginning of an 800 kHz cycle

          ^

OctoWS2811Ext.cpp:213: error: 'FTM2_CNT' was not declared in this scope

   while (FTM2_CNT < cv) ;

          ^

OctoWS2811Ext.cpp:214: error: 'FTM2_SC' was not declared in this scope

   FTM2_SC = 0;             // stop FTM2 timer (hopefully before it rolls over)

   ^

OctoWS2811Ext.cpp:215: error: 'FTM2_CNT' was not declared in this scope

   FTM2_CNT = 0;

   ^

OctoWS2811Ext.cpp:218: error: 'PORTB_ISFR' was not declared in this scope

   PORTB_ISFR = (1<<18);    // clear any prior rising edge

   ^

OctoWS2811Ext.cpp:229: error: 'FTM_SC_CLKS' was not declared in this scope

   FTM2_SC = FTM_SC_CLKS(1) | FTM_SC_PS(0); // restart FTM2 timer

                          ^

OctoWS2811Ext.cpp:229: error: 'FTM_SC_PS' was not declared in this scope

   FTM2_SC = FTM_SC_CLKS(1) | FTM_SC_PS(0); // restart FTM2 timer

                                         ^

'GPIOD_PCOR' was not declared in this scope

**Comment by fat-fred** [comment]
There is a PR From me for Teensy 4
https://github.com/DirectOutput/TeensyStripController/pull/7

**Comment by Pittyh** [comment]
> There is a PR From me for Teensy 4
> #7

Yes thank you i saw that, and managed to install it on the Teensy4.0

But DOF is reporting error Teensystripcontroller not found.
Warning: Output controller type TeensyStripController not found during deserialization of data.

Do you have DOF working on the Teensy4.0? i just want to know if it's actually possible?
So I'm not sure if it's because of your branch, or the Teensy 4 just doesn't work with DOF?
Maybe i need to update my DOF, It's all very confusing.




2020.10.12 00:17:40.475 DirectOutput Logger initialized

2020.10.12 00:17:40.476 DirectOutput Version 0.8.5307.1702 as of 2014.07.13 00:56
2020.10.12 00:17:40.476 Global config loaded from: K:\DIRECTOUTPUT\config\GlobalConfig_B2SServer.xml
2020.10.12 00:17:40.476 Loading Pinball parts
2020.10.12 00:17:40.476 Loading cabinet
2020.10.12 00:17:40.477 Will load cabinet config file: K:\DirectOutput\Config\Cabinet.xml
2020.10.12 00:17:40.543 Warning: Output controller type TeensyStripController not found during deserialization of data.
2020.10.12 00:17:40.573 0 output controller defnitions and 3 toy definitions loaded from cabinet config.
2020.10.12 00:17:40.573 Cabinet config file has AutoConfig feature enabled. Calling AutoConfig.
2020.10.12 00:17:40.574 Cabinet auto configuration started
2020.10.12 00:17:40.648 Cabinet auto configuration finished
2020.10.12 00:17:40.648 Autoconfig complete.
2020.10.12 00:17:40.648 Cabinet config loaded successfully from K:\DirectOutput\Config\Cabinet.xml
2020.10.12 00:17:40.648 Cabinet loaded
2020.10.12 00:17:40.648 Loading table config
2020.10.12 00:17:40.649 Warning: No table config file found. Will try to load config from LedControl file(s).
2020.10.12 00:17:40.649 Will try to load configs from DirectOutput.ini or LedControl.ini file(s) for RomName mm_109c
2020.10.12 00:17:40.651 Loading LedControl file K:\DIRECTOUTPUT\config\directoutputconfig30.ini
2020.10.12 00:17:40.709 EXCEPTION: Table with ShortRomName Galaxie_1971 has already been loaded (Exists more than once in ledcontrol file).
2020.10.12 00:17:40.709 EXCEPTION: Thread: 
2020.10.12 00:17:40.711 EXCEPTION: Table with ShortRomName Big_Shot_1974 has already been loaded (Exists more than once in ledcontrol file).
2020.10.12 00:17:40.711 EXCEPTION: Thread: 
2020.10.12 00:17:40.744 EXCEPTION: Table with ShortRomName SpotPool_1976 has already been loaded (Exists more than once in ledcontrol file).
2020.10.12 00:17:40.744 EXCEPTION: Thread: 
2020.10.12 00:17:40.769 1 directoutputconfig.ini or ledcontrol.ini files loaded.
2020.10.12 00:17:40.770 Config for RomName mm_109c exists in LedControl data. Updating cabinet and config.
2020.10.12 00:17:40.791 Table config loading finished
2020.10.12 00:17:40.791 Pinball parts loaded
2020.10.12 00:17:40.791 Starting processes
2020.10.12 00:17:40.792 Initializing cabinet
2020.10.12 00:17:40.795 Cabinet initialized
2020.10.12 00:17:40.797 Framework initialized.
2020.10.12 00:17:40.797 Have fun! :)


CABINET.XML


```<?xml version="1.0" encoding="utf-8"?>
<!-- This config file will set up two addressable LED strips orange on the right and blue on the left.  Each is 53 long and have the distal LED as the first in the array -->
<Cabinet xmlns:xsi="http://www.w3.org/20...chema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Name>MultiBall</Name> Cabinet Name
  <OutputControllers>
    <TeensyStripController> 
      <Name>TeensyStripController</Name>
      <NumberOfLedsStrip1>144</NumberOfLedsStrip1>  Number of LEDs on the right playfield 
      <NumberOfLedsStrip2>144</NumberOfLedsStrip2>  Number of LEDs on the left playfield
      <NumberOfLedsStrip3>0</NumberOfLedsStrip3>
      <NumberOfLedsStrip4>0</NumberOfLedsStrip4>
      <NumberOfLedsStrip5>0</NumberOfLedsStrip5>
      <NumberOfLedsStrip6>0</NumberOfLedsStrip6>
      <NumberOfLedsStrip7>0</NumberOfLedsStrip7>
      <NumberOfLedsStrip8>0</NumberOfLedsStrip8>
      <ComPortName>COM4</ComPortName> You must look in device manager to see what port Windows assigned for the Teensy USB connection.
    </TeensyStripController>
  </OutputControllers>
  <Toys>
    <LedStrip>
      <Name>PF Right</Name> This is the name that I gave the right playfield strip
      <Width>1</Width> These strips run as one long string as far as the Teensy board is concerned.  If you set the width to anything other than 1 it will give you funny results like the entire strip being LED 1
      <Height>144</Height> This is the length of the right playfield LED array
      <LedStripArrangement>TopDownLeftRight</LedStripArrangement> There are several choices that can be used here like BottomUpLeftRight.  This determines the order of LEDs that the Teensy sends out on its signal path.  If you use TopDown then the furthest LED from the connecting wires will be the first one in the segnal pathway.  I needed this because I wanted my Teensy Board in the back of the machine by the power supplies to make the shorted wiring runs.
      <ColorOrder>GRB</ColorOrder>  You must choose GRB not RBG with these strips to get them to correctly display the colors sent to them
      <FirstLedNumber>1</FirstLedNumber> This is the first strip so it starts with LED 1
      <FadingCurveName>SwissLizardsLedCurve</FadingCurveName> I didn't play with this setting so I can't tell you what this does but I suspect that this sets the protocol that DOF uses for lighting the strips.
      <OutputControllerName>TeensyStripController</OutputControllerName>
    </LedStrip>
    <LedStrip>
      <Name>PF Left</Name> This strip is set up just like the other with exceptions in bold
      <Width>1</Width>
      <Height>144</Height>
      <LedStripArrangement>TopDownLeftRight</LedStripArrangement>
      <ColorOrder>GRB</ColorOrder>
      <FirstLedNumber>1</FirstLedNumber> Since this is the second strip its first LED is the next one after the last LED on the other strip so since my strips are 53 LEDs long it is LED 54.
      <FadingCurveName>SwissLizardsLedCurve</FadingCurveName>
      <OutputControllerName>TeensyStripController</OutputControllerName>
    </LedStrip>
    <LedWizEquivalent>
       <Name>LedWizEquivalent 30</Name> This is the number assigned to the WS2811 controller by the online DOF config tool
      <Outputs>
        <LedWizEquivalentOutput>
          <OutputName>PF Right</OutputName> Name as defined above
          <LedWizEquivalentOutputNumber>1</LedWizEquivalentOutputNumber> This is the port number of the first set of combos set up In the online DOF Config tool so it is port 1
        </LedWizEquivalentOutput> 
        <LedWizEquivalentOutput>
          <OutputName>PF Left</OutputName> Name as defined above
          <LedWizEquivalentOutputNumber>4</LedWizEquivalentOutputNumber> This is the port number of the second set of combos set up in the online DOF config tool so it is port 4
        </LedWizEquivalentOutput>
      </Outputs>
     <LedWizNumber>30</LedWizNumber>
    </LedWizEquivalent> 
  </Toys>
 <AutoConfigEnabled>true</AutoConfigEnabled> This needs to be set to true to work
</Cabinet>

**Comment by fat-fred** [comment]
Perhaps the wrong com-Port?
Had also Problems to configure it. 
for this i include the „Test-Mode“ over serial. 
Open an serial console (putty) and press „t“. 
All LEDs Should Then Go on.

**Comment by Pittyh** [comment]
ok thanks i will try that.

Did you manage to get the teensy4.0 working with DOF in the end?

Regards.

**Comment by fat-fred** [comment]
Yes. It Works for me

**Comment by Pittyh** [comment]
ok so i tried T in putty and it works, the board LED flashes quickly, so problem must lie elsewhere.

**Comment by fat-fred** [comment]
Yes. The board is ok and working.

**Comment by Pittyh** [comment]
Thanks, got it working, seems this Pull Request works great, was just a DOF config issue (my fault)
